### ISSUE TITLE
Question: why not translate in the rendering engine

### ISSUE THREAD

**Issue by jcalfee** [martinandert/react-translate-component#13]
Seems like one could apply translations in react's DOM patch before it hits the real DOM.  A simple set of regular expressions would take most of the translations out of the code and move it into the external translation resources.  This seems more consistent with modern localization software in my experience.  

Please comment...  Thank you.

**Comment by martinandert** [comment]
@jcalfee Sorry but I don't get it. Could you give me an example (a gist) of what you're trying to achieve?

Thanks

**Comment by martinandert** [comment]
Closing because of staleness.

**Comment by jcalfee** [comment]
I'm just suggesting to not have translations in the code and instead move it to the dom rendering layer.  This will save a ton of effort on the part of the coders.  In react this needs to happen in a way so that reacts DOM comparison is always translating then comparing to the translated DOM.  You can still put translations in the code, most of the tedious translation work will not be needed anymore.

**Comment by jcalfee** [comment]
I apologize, I missed your first comment.
