### ISSUE TITLE
Can't translate from Array

### ISSUE THREAD

**Issue by pistou** [martinandert/react-translate-component#16]
I'm trying to translate from an Array
For instance:

*en.js*
```
module.exports = {
    foo: {
        bar: [
            {
                lorem: "ipsum",
                some: "text"
            }
        ]
    }
};
```

*component.jsx*
```
<Translate content="foo.bar[0].lorem" />
```

At this point, all I get is

> missing  translation: en.foo.bar[0].lorem

Is there a way to achieve this?

**Comment by martinandert** [comment]
Unfortunately, translating from arrays is not supported at the moment. I'm not sure if this is a good feature to have.
