### ISSUE TITLE
Expose onLocaleChange from counterpart

### ISSUE THREAD

**Issue by raoulus** [martinandert/react-translate-component#23]
Hi,

in my app I need to have a listener when the locale changes (in order to switch custom monetary formats). Currently I have to do this directly with counterpart, but I think it would be useful to expose this functionality inside the react-translate-component as well.

`
module.exports.onLocaleChange = translator.onLocaleChange.bind(translator);
`

What do you think?

**Comment by martinandert** [comment]
Hi @raoulus, no objections from my side. Happy to accept a pull request which adds this functionality. Please also expose `offLocaleChange` as well.

**Comment by raoulus** [comment]
cool, going to prepare a PR.

thanks!

**Comment by raoulus** [comment]
Please check #24
