### ISSUE TITLE
Problem in select option

### ISSUE THREAD

**Issue by briva** [martinandert/react-translate-component#25]
Hello,

From this issue : https://github.com/martinandert/react-translate-component/issues/20

I'm trying to translate my option select.

But with : 

`<Translate {...this.props} component="option" key={0} value={0} content={"key_lang"} />`

It working well but i get a warning :

> warning.js:36 Warning: Unknown prop `coverComponent` on <option> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

Thanks

**Comment by martinandert** [comment]
Hi @briva, could you please show me what's inside `this.props` in your example?
