### ISSUE TITLE
Can't make dynamic translation work using `with`

### ISSUE THREAD

**Issue by micky2be** [martinandert/react-translate-component#28]
I have a simple label  `"Inbox": "Inbox [%(unread)]"` showing the number of unread message.
I setting the props `with` like so `{ unread: nbUnreadMsg || 0 }` but the display stay as `Inbox [%(unread)]`

This number can change dynamically of course and will trigger a rendering on this comonent.
Am I missing something here?

**Comment by martinandert** [comment]
Hi @micky2be, please try `%(unread)s` instead of `%(unread)`. See https://www.npmjs.com/package/sprintf-js#named-arguments.
