### ISSUE TITLE
React 15.5 deprecation warnings

### ISSUE THREAD

**Issue by polco** [martinandert/react-translate-component#32]
React 15.5.0 introduced to major deprecations:  ```React.createClass``` and ```React.propTypes```
https://github.com/facebook/react/releases/tag/v15.5.0

would be nice to get rid of those :)

**Comment by briva** [comment]
Yep, same issue :)

**Comment by martinandert** [comment]
Fixed in v0.14.

**Comment by polco** [comment]
clean console again ! thanks
