### ISSUE TITLE
Translate without <span> tag

### ISSUE THREAD

**Issue by athanph** [martinandert/react-translate-component#33]
Is there a way to translate without outputting the `<span>` tag wrapper?
Anyway to configure this globally? Thanks.

**Comment by martinandert** [comment]
Not currently. But you can pass any component to `Translate` so it's not wrapped in a `<span>`.

So instead of

```jsx
<p className="foo"><Translate ... /></p>
```

you can do

```jsx
<Translate  ... component="p" className="foo" />
```

This also works for React classes:

```jsx
<MyComponent some="prop"><Translate ... /></MyComponent>
```

becomes

```jsx
<Translate ... component={MyComponent} some="prop" />
```
