### ISSUE TITLE
Escape the % Character 

### ISSUE THREAD

**Issue by saczuac** [martinandert/react-translate-component#40]
Hi!,

When the JSON string has a "%" character the translator fails, raise the following error in console:

Uncaught SyntaxError: [sprintf] unexpected placeholder.

example JSON translate:

```javascript
{
  "fee": "The fee is 4%"
}
```

**Comment by martinandert** [comment]
I think you need two percent signs to escape the '%' character: `"The fee is 4%%"`.

**Comment by saczuac** [comment]
Thanks! it was the solution
