### ISSUE TITLE
Make Language Switcher work with "counterpart.translate"

### ISSUE THREAD

**Issue by OfficialCRUGG** [martinandert/react-translate-component#41]
Hey there!
I am currently working on my first real react project, and stumbled over a little problem. Once I implemented a language changer, it perfectly changes the translation of all <Translate> Elements, but not of all elements that use counterpart.translate.
I have some Elements in my Code, where I can't use the <Translate> Element, so I had to use counterpart.translate. Here is an example:
```jsx
<Link to="/blog" className="footer-link">{counterpart.translate("footer.community.blog")}</Link>
```
Does anybody haven an Idea on how I could refresh those as well?

**Comment by martinandert** [comment]
Maybe this helps (untested): https://gist.github.com/martinandert/c9ad5051833014e126f9e28c1911f09f
