### ISSUE TITLE
Support HTML content

### ISSUE THREAD

**Issue by jonaswindey** [martinandert/react-translate-component#7]
At the moment it's not possible to set html content in the translation values.

If I use:

`<div dangerouslySetInnerHTML={{__html: _t('my_translation')}} />`

it just renders [Object object] instead of the translated string.

**Comment by martinandert** [comment]
I think the example code uses a translation with embedded HTML. See https://github.com/martinandert/react-translate-component/blob/master/example/locales/en.js under `example.seconds_passed`.

Does that help?
